#!/usr/bin/env python3
"""Harvest raw remote compactions from the calling account's own Responses traffic.

For each (model, target_size, threshold) cell: build a synthetic multi-turn
conversation of deterministic filler (NO real secrets), request a Responses
create with server-side compaction, capture the stream, and record:
  - full raw SSE
  - compaction item(s) (id, encrypted_content, token_count if present)
  - encrypted reasoning items if the stream emits them
  - usage (input/output/reasoning tokens)
  - envelope stats (len, prefix, count)

Appends one JSON record per run to a JSONL dataset file.
First-party only: all content is synthetic, generated by this account.
"""
import json, os, sys, time, hashlib, argparse
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from codex_responses import collect_response

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def make_filler_sections(words_per_section=140, n=80, topic=None):
    """Deterministic synthetic filler (word salad about a fake pipeline)."""
    topics = {
        "pipeline": [
            "The async reconciler drains the outbox in waves of at most 512 rows; each row is stamped "
            "with a strictly increasing salt, then hashed through SHA-256 with the preceding row's "
            "digest to form a compact chain. On a tombstone the drainer backfills the gap with a "
            "sentinel and marks the partition for rewrite at the next checkpoint. Backpressure is "
            "shed by holding the wavemeter above a high-water mark while the mirror sidecar "
            "ACKs in batches of eight, preserving at-most-once semantics without a carrier-grade lock.",
            "Quarantine rings index excess messages by a rotated Bloom filter whose false-positive "
            "rate is capped at one percent; entries older than the retention window are swept by a "
            "janitor that runs on a quiet schedule to avoid contending with the hot registry. Each "
            "swept cell emits a metric so the operator can verify the drain rate stays above the "
            "committed floor before backfilling from the cold tier of object storage.",
            "The snapshotter alternates between a full merge and an incremental diff, keyed by the "
            "generation number carved into the manifest. Compaction candidate files are graded by "
            "how much garbage they carry; the grader prefers files whose live ratio is below a "
            "threshold, then orders them by size so the largest reclaims attract the most candidates "
            "per pass. After each pass a new manifest is persisted and the obsolete files are "
            "quarantined for a grace period before final deletion.",
        ],
    }
    blocks = []
    ring = topics.get(topic or "pipeline")
    for i in range(n):
        blocks.append(f"Section {i}: " + ring[i % len(ring)])
    return "\n\n".join(blocks)


def make_conversation(target_chars=None, target_tokens=None, rounds=6):
    """Deterministic multi-turn conversation; user + assistant turns."""
    conv = []
    for i in range(rounds):
        conv.append({"role": "user", "content": f"Turn {i} instruction: {make_filler_sections(words_per_section=120, n=10)}"})
        conv.append({"role": "assistant", "content": f"Turn {i} response: acknowledged block {i}; continuity vector {i*7}."})
    return conv


def run_cell(model, threshold, target_tokens=20000, reasoning=None, label="", out_prefix=""):
    conv = make_conversation(target_tokens=target_tokens)
    # estimate: ~4 chars/token
    body = {
        "model": model,
        "input": conv,
        "store": False,
        "stream": True,
        "context_management": [{"type": "compaction", "compact_threshold": threshold}],
    }
    if reasoning:
        body["reasoning"] = {"effort": reasoning}
    stamp = int(time.time() * 1000)
    raw_path = os.path.join(ROOT, "raw", f"{out_prefix or model}-{label}-{stamp}.sse")
    try:
        res = collect_response(body, save_raw=raw_path, timeout=900)
    except Exception as e:
        return {"ok": False, "error": str(e), "model": model, "threshold": threshold, "label": label}

    compaction_items = []
    reasoning_items = []
    for it in res["items"]:
        t = it.get("type")
        if t == "compaction":
            compaction_items.append({
                "id": it.get("id"),
                "encrypted_content": it.get("encrypted_content"),
                "token_count": it.get("token_count"),
            })
        elif t == "reasoning":
            reasoning_items.append({
                **({"id": it.get("id")} if it.get("id") else {}),
                "kind": "reasoning",
                "encrypted_content": it.get("encrypted_content"),
                "summary": it.get("summary"),
                "content": it.get("content"),
                "full_item": it,
            })
        elif t == "message":
            pass

    rec = {
        "ok": True,
        "run_id": stamp,
        "ts": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "model": model,
        "threshold": threshold,
        "label": label,
        "usage": res.get("usage"),
        "status": res.get("status"),
        "errors": res.get("errors", [])[:3],
        "raw_sse_path": raw_path,
        "n_compaction_items": len(compaction_items),
        "n_reasoning_items": len(reasoning_items),
        "compaction_items": compaction_items,
        "reasoning_items": reasoning_items,
        "conversation_sha256": hashlib.sha256(json.dumps(conv, sort_keys=True).encode()).hexdigest()[:16],
        "conversation_chars": sum(len(c["content"]) for c in conv),
    }
    return rec


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--models", default="gpt-5.6-luna")
    ap.add_argument("--thresholds", default="1000,5000", help="comma thresholds")
    ap.add_argument("--reasoning", default=None)
    ap.add_argument("--label", default="")
    ap.add_argument("--out", default=os.path.join(ROOT, "raw", "harvest.jsonl"))
    ap.add_argument("--repeats", type=int, default=1)
    args = ap.parse_args()

    results = []
    for model in [m.strip() for m in args.models.split(",") if m.strip()]:
        for th in [int(t) for t in args.thresholds.split(",") if t.strip()]:
            for r in range(args.repeats):
                rec = run_cell(model, th, reasoning=args.reasoning,
                               label=f"{args.label}{('-r'+str(r) if args.repeats>1 else '')}", out_prefix=model)
                line = json.dumps(rec)
                results.append(rec)
                with open(args.out, "a") as f:
                    f.write(line + "\n")
                print(line[:400])
    print(f"\nWrote {len(results)} records to {args.out}")
